name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Prepare Dockerfile
      run: cp ./docker/Dockerfile.backend ./Dockerfile
      working-directory: backend

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      working-directory: backend

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./docker/Dockerfile.backend
        push: true
        tags: sailesh11/event-management-system:latest

    - name: Verify Pushed Image
      run: docker pull sailesh11/event-management-system:latest
      working-directory: backend

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull sailesh11/event-management-system:latest
          sudo docker stop event-management-system || true
          sudo docker rm event-management-system || true
          sudo docker run -d --name event-management-system -p 3005:3000 sailesh11/event-management-system:latest
        working-directory: backend